version: "3.9"
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./scripts/nginx-docker.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - "registry"
      - "web"
      - "end-user-portal"
    ports:
      - "35291:35291"
      - "35293:35293"
    networks:
      - speakeasy_charts_network
  registry:
    image: gcr.io/linen-analyst-344721/speakeasy-api/registry:sha-df470c5
    environment:
      - SPEAKEASY_ENVIRONMENT=docker
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/registry?sslmode=disable
      - PORTAL_DOMAIN=.localhost:35291
    volumes:
      - ~/.config/:/root/.config
    ports:
      - "35290:35290"
      - "35300:35300"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - speakeasy_charts_network
  web:
    image: gcr.io/linen-analyst-344721/speakeasy-api/web:sha-df470c5
    networks:
      - speakeasy_charts_network
    volumes:
      - ~/.config/:/root/.config
  embed-fixture:
    image: gcr.io/linen-analyst-344721/speakeasy-api/embed-fixture:sha-df470c5
    networks:
      - speakeasy_charts_network
    volumes:
      - ~/.config/:/root/.config
    ports:
      - "35292:35292"
  end-user-portal:
    image: gcr.io/linen-analyst-344721/speakeasy-api/end-user-portal:sha-df470c5
    networks:
      - speakeasy_charts_network
    environment:
      SERVER_URL: http://localhost:35290
    volumes:
      - ~/.config/:/root/.config
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registry
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - speakeasy_charts_network
networks:
  speakeasy_charts_network:
    name: speakeasy_charts_network
