version: "3.9"
services:
  registry:
    image: gcr.io/linen-analyst-344721/speakeasy-api/registry:release-1.1.0
    environment:
      - SPEAKEASY_ENVIRONMENT=docker
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/registry?sslmode=disable
    volumes:
      - ~/.config/:/root/.config
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - speakeasy_charts_network
  web:
    image: gcr.io/linen-analyst-344721/speakeasy-api/web:release-1.1.0
    networks:
      - speakeasy_charts_network
    volumes:
      - ~/.config/:/root/.config
    ports:
      - "3000:3000"
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registry
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - speakeasy_charts_network
networks:
  speakeasy_charts_network:
    name: speakeasy_charts_network
