{{- if index .Values "cert-manager" "enabled" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "letsencrypt" }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    email: {{ .Values.notificationEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: speakeasy-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
  {{- if index ".Values.external-dns.enabled" }}
    {{- with ".Values.external-dns.providers" }}
    - dns01:
        {{ ".Values.external-dns.provider" | toYaml}}:
    {{- end }}
      selector:
        dnsNames: |-
          - {{ ".Values.external-dns.portalWildcardDomain"  }}
  {{- end }}
{{- end }}
