{{- if index .Values "cert-manager" "enabled" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "letsencrypt" }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    email: {{ .Values.notificationEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: speakeasy-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
  {{- if .Values.portal.enabled }}
    - dns01:
        {{ .Values.portal.provider }}:
        {{- if eq .Values.portal.provider "cloudDNS" }}
          project: {{ .Values.portal.project }}
          serviceAccountSecretRef:
          {{- range $k, $v := .Values.portal.serviceAccountSecretRef }}
            {{ $k }}: {{ $v }}
          {{- end }}
        {{- end }}
        {{- if eq .Values.portal.provider "route53" }}
          region: {{ .Values.portal.region }}
          role: {{ .Values.portal.role }}
        {{- if .Values.portal.hostedZoneID }}
          hostedZoneId: {{ .Values.portal.hostedZoneID }}
        {{- else }}
          accessKeyId: {{ .Values.portal.accessKeyID }}
          secretAccessKeySecretRef:
          {{- range $k, $v := .Values.portal.secretAccessKeySecretRef }}
          {{ $k }}: {{ $v }}
          {{- end}}
        {{- end }}
        {{- end }}
      selector:
        dnsNames:
          - {{ .Values.portal.portalWildcardDomain | quote }}
  {{- end }}
{{- end }}
