{{- if index .Values "cert-manager" "enabled" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: speakeasy-speakeasy-k8s-letsencrypt
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    email: anuraag@speakeasyapi.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: speakeasy-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
