{{- if or (index .Values "cert-manager" "enabled") .Values.createCertManagerResources -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "letsencrypt" }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    email: {{ .Values.notificationEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: speakeasy-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        {{ .Values.dns.provider }}:
        {{- if eq .Values.dns.provider "cloudDNS" }}
          project: {{ .Values.dns.project }}
          serviceAccountSecretRef:
          {{- range $k, $v := .Values.dns.serviceAccountSecretRef }}
            {{ $k }}: {{ $v }}
          {{- end }}
        {{- end }}
        {{- if eq .Values.dns.provider "route53" }}
          region: {{ .Values.dns.region }}
          role: {{ .Values.dns.role }}
        {{- if .Values.dns.hostedZoneID }}
          hostedZoneId: {{ .Values.dns.hostedZoneID }}
        {{- else }}
          accessKeyId: {{ .Values.dns.accessKeyID }}
          secretAccessKeySecretRef:
          {{- range $k, $v := .Values.dns.secretAccessKeySecretRef }}
          {{ $k }}: {{ $v }}
          {{- end}}
        {{- end }}
        {{- end }}
      selector:
        dnsNames:
        {{- range $v := .Values.registry.ingress.registryHostnames }}
          - {{ $v | quote }}
        {{- end }}
        {{- range $v := .Values.posthogProxy.hosts }}
          - {{ $v | quote}}
        {{- end}}
{{- end }}