{{- if index .Values "cert-manager" "enabled" -}}
{{- if or .Values.cert-manager.enabled .Values.createClusterIssuer -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "letsencrypt" }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    email: {{ .Values.notificationEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: speakeasy-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
