{{- if (and .Values.registry.ingress.enabled (or .Values.registry.ingress.apiHostnames .Values.registry.ingress.webHostnames)) -}}
{{- $serviceName := printf "%s-%s" (include "speakeasy-registry.fullname" .) "service" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "ingress" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/grpc-services: {{ $serviceName }}
    cert-manager.io/cluster-issuer: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "letsencrypt" }}
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    {{- include "speakeasy-registry.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        {{- range $v := .Values.registry.ingress.apiHostnames }}
        - {{ $v }}
        {{- end }}
        {{- range $v := .Values.registry.ingress.webHostnames }}
        - {{ $v }}
        {{- end }}
      secretName: nginx-letsencrypt-registry
  rules:
    {{- range $v := .Values.registry.ingress.webHostnames }}
    - host: {{ $v }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 80
            path: /v1/
            pathType: Prefix
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 81
            path: /
            pathType: Prefix
    {{- end }}
    {{- range $v := .Values.registry.ingress.apiHostnames }}
    - host: {{ $v }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 80
            path: /
            pathType: Prefix
    {{- end }}
{{- end }}