{{- $secret_name := "jwt-secret-key-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
data:
  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  {{- if or (not $old_sec) (not $old_sec.data) }}
  jwtSecretKey: {{ randAlphaNum 128 | b64enc }}
  {{ else }}
  jwtSecretKey: {{ index $old_sec.data "jwtSecretKey" }}
  {{ end }}