{{- if gt (len .Values.posthogProxy.hosts) 0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.posthogProxy.serviceName | quote}}
spec:
  type: ExternalName
  externalName: app.posthog.com
  ports:
    - name: https
      protocol: TCP
      port: 443
{{- end}}
