{{- $serviceName := printf "%s-%s" (include "speakeasy-registry.fullname" .) "service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "speakeasy-registry.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 35290
      protocol: TCP
      name: http
    - port: 90
      targetPort: 35300
      protocol: TCP
      name: grpc
    - port: 81
      targetPort: 35291
      protocol: TCP
      name: web
    - port: 82
      targetPort: 35292
      protocol: TCP
      name: embed
  selector:
    {{- include "speakeasy-registry.selectorLabels" . | nindent 4 }}
