# Redpanda production deployments require xfs filesystem (https://docs.redpanda.com/docs/manage/kubernetes/configure-storage/#use-persistentvolumes)
# Redpanda folks pointed me to https://medium.com/@allanlei/mounting-xfs-on-gke-adcf9bd0f212
# This is the result of me cobbling this together
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redpanda-sc
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fstype: xfs
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true