{{- if  .Values.auth.GithubClientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.GithubClientSecretName }}
data:
  {{ .Values.auth.GithubClientSecretKey }}: {{ .Values.auth.GithubClientSecret | b64enc }}
{{- end }}
