apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ambassador-web-cert
spec:
  secretName: ambassador-web-cert
  issuerRef:
    name: speakeasy-letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - $YOUR_WEB_HOSTNAME$
