---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: speakeasy-web
spec:
  hostname: $YOUR_WEB_HOSTNAME$
  tlsSecret:
    name: ambassador-web-cert
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-web-api
spec:
  hostname: $YOUR_WEB_HOSTNAME$
  prefix: /v1/
  rewrite: /v1/
  service: speakeasy-service
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-web-grpc
spec:
  hostname: $YOUR_WEB_HOSTNAME$
  grpc: True
  prefix: /grpc
  service: speakeasy-service:90
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-web
spec:
  hostname: $YOUR_WEB_HOSTNAME$
  prefix: /
  service: speakeasy-service:81

