---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: speakeasy-web
spec:
  hostname: $YOUR_WEB_HOSTNAME$ 
  tlsSecret:
    name: ambassador-web-cert
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: speakeasy-grpc
spec:
  hostname: $YOUR_GRPC_HOSTNAME$ 
  tlsSecret:
    name: ambassador-grpc-cert
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-web-api
spec:
  hostname: $YOUR_WEB_HOSTNAME$ 
  prefix: /v1/
  rewrite: /v1/
  service: speakeasy-service
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-web
spec:
  hostname: $YOUR_WEB_HOSTNAME$ 
  prefix: /
  service: speakeasy-service:81
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-embed-fixture
spec:
  hostname: $YOUR_EMBED_FIXTURE_HOSTNAME$
  prefix: /
  service: speakeasy-service:82
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-portal
spec:
  hostname: $YOUR_PORTAL_HOSTNAME$
  prefix: /
  # TODO: point to portal port
  service: speakeasy-service:81
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: speakeasy-grpc
spec:
  hostname: $YOUR_GRPC_HOSTNAME$ 
  grpc: True
  prefix: /
  service: speakeasy-service:90

