---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
spec:
  port: 8080
  protocol: HTTPS  # NOT A TYPO, see below
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: https-listener
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: acme-challenge-mapping
spec:
  hostname: "*"
  rewrite: ""
  prefix: /.well-known/acme-challenge/
  service: acme-challenge-service
---
apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-service
spec:
  ports:
    - port: 80
      targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: speakeasy-letsencrypt
spec:
  acme:
    email: $YOUR_EMAIL_HERE$
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: speakeasy-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
