{{- if and .Values.registry.ingress.enabled .Values.registry.dns -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "registry-certs" }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "speakeasy-registry.gen-certs" . ) | indent 2 }}
{{- end}}