apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ printf "%s-%s" (include "speakeasy-registry.fullname" .) "root-web-certs" }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "speakeasy-root-web.gen-certs" . ) | indent 2 }}