apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
spec:
  encryptedData:
    githubClientSecret: <MY_SEALED_SECRET>
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-client-secret
